services:
  - type: web
    name: iris-flask-api
    env: python
    runtime: 3.10
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app/main.py"
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8000