name: CI/CD for Iris Project (Flask)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
       PYTHONPATH=. pytest

  # cd:
  #   name: Continuous Deployment (Flask)
  #   runs-on: ubuntu-latest
  #   needs: ci
  #   if: github.ref == 'refs/heads/main'

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4

  #   - name: Set up Python
  #     uses: actions/setup-python@v5
  #     with:
  #       python-version: '3.10'

  #   - name: Install dependencies
  #     run: |
  #       pip install -r requirements.txt

  #   - name: Train and Save Model
  #     run: |
  #       python -c "from app.model import train_and_save_model; train_and_save_model()"

  #   - name: Start Flask Server (for demo test)
  #     run: |
  #       nohup python app/main.py &
  #       sleep 5
  #       curl http://127.0.0.1:8000/
